# Generated by Django 4.2.4 on 2024-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='creator_type',
            field=models.SmallIntegerField(choices=[(0, 'unknown'), (1, 'person'), (2, 'group'), (3, 'person & group')], default=0),
        ),
    ]
