# Generated by Django 4.2.4 on 2024-08-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_creator_creator_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='other_related_projects',
            field=models.ManyToManyField(to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectSeriesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('projectseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectseries')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='related_series',
            field=models.ManyToManyField(through='core.ProjectSeriesEntry', to='core.projectseries'),
        ),
    ]
