# Generated by Django 4.2.4 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectseries_project_other_related_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectseriesentry',
            name='order_num',
            field=models.FloatField(default=0),
        ),
    ]
