# Generated by Django 4.2.4 on 2024-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectseriesentry_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectseriesentry',
            name='order_num',
            field=models.FloatField(default=-1024),
        ),
    ]
